version: 3
services:
 homarr:
  container_name: homarr
  image: ghcr.io/ajnart/homarr:latest
  ports:
   - 80:7575
  volumes:
   - /docker/homarr/config:/app/data/configs
   - /docker/homarr/icons:/app/public/icons
   - /var/run/docker.sock:/var/run/docker.sock
  restart: unless-stopped
 jellyfin:
  container_name: jellyfin
  image: jellyfin/jellyfin
  network_mode: host
  volumes:
   - /docker/jellyfin/config:/config
   - /docker/jellyfin/cache:/cache    
   - /media:/media   
  restart: unless-stopped
 portainer:
  container_name: portainer
  image: portainer/portainer-ce:latest
  ports:
   - 9000:9000
  volumes:
   - /docker/portainer/data:/data
   - /var/run/docker.sock:/var/run/docker.sock
  restart: always
 transmission:
  container_name: transmission
  image: 	lscr.io/linuxserver/transmission:latest
  ports:
   - 9091:9091
   - 51413:51413
   - 51413:51413/udp
  volumes:
   - /docker/transmission/config:/config
   - /media:/downloads
  environment:
   - PUID=1000
   - PGID=1000
##########################################################
#                                                        #
#                CHANGE USER AND PASSWORD                #
#                                                        #
##########################################################
   - USER=admin
   - PASS=Pa$$w0rd
  restart: unless-stopped
##########################################################
#                  BEFORE INSTALLATION                   #
#                                                        #
#     git clone https://github.com/ole-vi/webssh.git     #
#                       cd webssh                        #
#                docker build -t webssh .                #
##########################################################
 webssh:
  container_name: webssh
  image: webssh
  ports:
   - 8888:8888